import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "youAreJust": "You are just",
          "oneStepAway": "One Step Away!",
          "registration": "Registration",
          "fName": "First Name",
          "lName": "Last Name",
          "phoneNumber": "Phone Number",
          "country": "Country",
          "password": "Password",
          "confirmPassword": "Confirm Password",
          "termsText1": "I, hereby, acknowledged and agreed to ",
          "termsText2": "Terms & Conditions ",
          "termsText3": "and ",
          "termsText4": "Privacy Policy ",
          "termsText5": "applied.",
          "emailAddress": "Email Address",
          "done": "Done",
          "welcomeText": "Welcome to LFR App!!",
          "mobileNumber": "Mobile Number",
          "enterYourMobileNumber": "Enter Your Mobile Number",
          "otpSentText": "OTP has been sent on your mobile number",
          "dontHaveAccount": "Don'\t have an account? ",
          "createAccount": "Create account",
          "loginWithEmailAddress": "Login with Email address",
          "login": "Login",
          "otpVerification": "OTP verification",
          "enterOtpSentOnYourMobile": "Enter OTP sent on your mobile number",
          "otp": "OTP",
          "didntReceivedOtp": "Didn't received OTP? ",
          "resendCode": "Resend code",
          "submit": "Submit",
          "enterYourEmailAddress": "Enter Your Email Address",
          "enterYourPassword": "Enter Your Password",
          "otpSentTextonEmailAddress":
              "OTP has been sent on your email address",
          "letsStartWithYour": "Lets Start With Your",
          "forgotPassword": "Forgot Password?",
          "forgotPassword2": "Forgot Password",
          "newUser": "New User? ",
          "signup": "Signup",
          "confirmForgotEmailDesc":
              "A confirmation otp will be sent to your email id",
          "changePassword": "Change Password",
          "newPassword": "New password",
          "welcome": "Welcome",
          "requiredFewSteps": "Required few steps",
          "vehicleRegistration": "Vehicle registration",
          "drivingLicense": "Driving License",
          "termsAndConditions": "Terms and Conditions",
          "vehicleName": "Vehicle name",
          "vehicleRegistrationNo": "Vehicle registration no",
          "next": "Next",
          "takeAPhotoOfYourLicenseFront":
              "Take a photo of your Driving License Front Side",
          "uploadOrTakePhoto": "Upload/take photo",
          "drivingLicenseNumber": "Driving license number",
          "expiryDate": "Expiry Date",
          "carefullyReadAllTAndC":
              "Carefully read all the Terms & Conditions applied.",
          "agreedTermsText": "I, hereby, read and agreed to all T&Cs.",
          "goToHomePage": "Go to Home Page",
          "congratulations": "Congratulations!",
          "congratsMsg":
              "You have completed all required steps to become a verified Delivery Agent. We’ll review your documents and contact you as soon as possible.",
          "home": "Home",
          "online": "Online",
          "logout": "Log Out",
          "loggedOut":"Logged Out Successfully",
          "youROffline": "You’re Offline",
          "youROnline": "You’re Online",
          "goOnline": "Go Online",
          "myOrders": "My Bookings",
          "active": "Active",
          "past": "Past",
          "bookingId": "Booking ID : ",
          "accept": "Accept",
          "reject": "Reject",
          "customerDetails": "Customer Details",
          "startTrip": "Start Trip",
          "cancel": "Cancel",
          "pickupPersonDetails": "Picked Up Person Details",
          "dropoffPersonDetails": "Drop off Person Details",
          "cancelBooking": "Cancel Booking",
          "pickupImage": "Pickup Image",
          "bookingStatus": "Booking Status : ",
          "delivered": "Delivered",
          "clickYourParcelPhoto": "Click your Parcel photo",
          "itemImages": "Item images",
          "photoRequirements": "Photo requirements",
          "photoRequirement1": "Keep your Parcel in the centre",
          "photoRequirement2": "Take photo in a bright well lit place",
          "photoRequirement3": "Make sure photo is not blurred",
          "pickedUp": "Picked-Up",
          "notification": "Notification",
          "myEarnings": "My Earnings",
          "currentWeek": "Current week",
          "history": "History",
          "breakdown": "Breakdown",
          "paid": "Paid",
          "orderId": "Booking ID",
          "dropOffDate": "Drop-off date & time",
          "amount": "Amount",
          "profile": "Profile",
          "changePassword2": "Change password?",
          "saveChanges": "Save Changes",
          "ongoingOrders": "Ongoing Bookings",
          "allOrders": "All Bookings",
          "new": "New",
          "orderDetails": "Booking Details",
          "newOrder": "New Booking",
          "pickup": "Pickup : ",
          "drop": "Drop : ",
          "tripDistance": "Trip Distance : ",
          "reachPickup": "Reach Pickup",
          "reachDrop": "Reach Drop",
          "goToMap": "Go to Map",
          "call": "Call",
          "pickupCustomerDetail": "Picked up customer details",
          "cancelOrder": "Cancel Booking",
          "reachedPickupLocation": "Reached Pickup Location",
          "recipientCustomerDetails": "Recipient customer details",
          "reachedDropLocation": "Reached Drop Location",
          "pickParcel": "Pick Parcel",
          "pickOrderIn2Mins": "Pick Booking in 2 mins",
          "document": "Document",
          "pickedParcel": "Picked Parcel",
          "dropParcel": "Drop Parcel",
          "parcelDelivered": "Parcel Delivered",
          "paidOnline": "Paid Online",
          "weight": "Weight",
          "cancelYourOrder": "Cancel Your Booking?",
          "chooseReason": "Choose reason",
          "cancelReason1": "Cancel delivery from customer",
          "cancelReason2": "Accidental food spillage",
          "cancelReason3": "Others",
          "cancelOrderPlaceholder": "Write down other reason, If any",
          "billAndItemImage": "Bill and Item Image",
          "packageDeliveredSafely": "Package was delivered safely",
          "deliveredBy": "Delivered by",
          "continue": "Continue",
          "noOrdersFound": "No Bookings Found",
          "parcelType": "Parcel Type",
          "paymentStatus": "Payment Status",
          "completed": "Completed",
          "cancelled": "Cancelled",
          "deliveredTo": "Delivered To",
          "bookingDate": "Booking Date",
          "earnings": "Earnings",
          "noOfBookings": "No of Bookings",
          "profileUnderReview":
              "Your account is under approval process. Please try again later.",
          "orderNo": "Order No.",
          "tripFare": "Trip Fare",
          "packageDetails": "Package Details",
          "type": "Type",
          "packageDescription": "Description",
          "deliveryInstructions": "Delivery Instructions",
          "deleteAccount": "Delete Account",
          "deleteAccountDesc": "Delete Account Permanently!",
          "confirm": "Confirm",
          "areYouSureYouWantToDeleteYourAccount":
              "Are you sure you want to delete your account?"
        },
      };
}
